### ISSUE TITLE
lorun的时间和内存出入

### ISSUE THREAD

**Issue by Rvelamen** [1510460325/judge#1]
你好，我这几天也在弄这个，你用的lorun计算出来的时间和内存有出入吗？我的出入挺大的，计算出来的结果都偏小

**Comment by 1510460325** [comment]
我看过源码，和hustoj判题一样，这个是调用linux内核完成的，和gdb调试是一样的，结果是比较准确的

**Comment by wangxiaoshuai-lucky** [comment]
> 
> 
> 你好，我这几天也在弄这个，你用的lorun计算出来的时间和内存有出入吗？我的出入挺大的，计算出来的结果都偏小

我看过源码，和hustoj判题一样，这个是调用linux内核完成的，和gdb调试是一样的，结果是比较准确的

**Comment by Rvelamen** [comment]
我用cf的数据和别人比赛中ac的代码，提交后结果跟cf平台上的结果出入挺大的

**Comment by wangxiaoshuai-lucky** [comment]
> 
> 
> 我用cf的数据和别人比赛中ac的代码，提交后结果跟cf平台上的结果出入挺大的

cf上的结果是每组都有一个结果吗？会不会是一个综合值呢

**Comment by Rvelamen** [comment]
每组都有一个结果，时间快了快一倍。。。

**Comment by wangxiaoshuai-lucky** [comment]
> 
> 
> 每组都有一个结果，时间快了快一倍。。。

暂时没找到cf系统源码，现在只有开源oj系统hustoj可以看到源码，但时间快了应该可以理解，可能与系统的并发数、判题步骤的复杂度有点关系。

**Comment by Rvelamen** [comment]
可是差了一倍的时间，有点难受😖😖😖😖

**Comment by wangxiaoshuai-lucky** [comment]
> 
> 
> 可是差了一倍的时间，有点难受😖😖😖😖

lorun是一个学长写的，从源码看判题流程还是非常准确的，相信cf的判题也应该类似，我写过一个demo，你可以参考参考这个流程，最难受的是这方面的资料网上不是很好找，只能从别人的开源源码入手

**Comment by Rvelamen** [comment]
那我换个机子测试一下，可能系统原因把

**Comment by Rvelamen** [comment]
你g++ 用的编译命令是怎么样的？

**Comment by wangxiaoshuai-lucky** [comment]
我的没做任何o1 o2 o3优化，就普通的-w忽略警告

**Comment by Rvelamen** [comment]
尴尬，不有话就超时了，内存就差不多。。
